#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI2 -d I II III
bspc monitor DP2 -d IV V VI

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color        "#184321"
bspc config normal_border_color         "#0b1f0f"
bspc config active_border_color         "#0b1f0f"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
feh --bg-color black "$@"
# Picom
# picom -CGb &
# Network Applet
#nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Noisetorch
noisetorch -i -t 95

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

# Clementine
clementine
